### ISSUE TITLE
fix profile information update

### ISSUE THREAD

**Issue by tykealy** [tykeaboyloy/Keyla4U-server#4]

**Comment by tykealy** [comment]
@vathanatork  checkout to 4-fix-profile-info to continue

<img width="802" alt="image" src="https://user-images.githubusercontent.com/87005466/234569935-90e1f833-daaa-4fbc-8699-fd256f6a16d5.png">

**Comment by vathanatork** [comment]
already fix it by changing validate rule for ProfileUpdateRequest
